// In this file you can specify the trial data for your experiment


const trial_info = {
    forced_choice: [
        {
            question: "Breakfast",
            option1: "Pausenbrot",
            option2: "Frühstück",
            correct: "Frühstück"

        },
        {
            question: "Cinnamon",
            option1: "Zimt",
            option2: "Stuhlbein",
            correct: "Zimt"

        },
        {
            question: "Eardrum",
            option1: "Ohrmuschel",
            option2: "Trommelfell",
            correct: "Trommelfell"

        },
        {
            question: "Forest",
            option1: "Wald",
            option2: "Holz",
            correct: "Wald"

        },
        {
            question: "Environment",
            option1: "Krankenhaus",
            option2: "Umwelt",
            correct: "Umwelt"

        }
    ],
    dropdown_choice_pe: [
        {
            QUD: "Fühlen",
            question: "<strong>The feeling of sweaty hands</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Geschmack",
            question: "<strong>Oranges</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Organisch",
            question: "<strong>The itch of a mosquito bite</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Geruch",
            question: "<strong>Summer rain on a hot day</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Kinästhetisch",
            question: "<strong>Clapping your hands</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        }
    ],
    dropdown_choice_pd: [
        {
            QUD: "Fühlen",
            question: "<strong>Das Gefühl schwitziger Hände</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Geschmack",
            question: "<strong>Orangen</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Organisch",
            question: "<strong>Das Jucken eines Mückenstichs</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Geruch",
            question: "<strong>Sommerregen an einem heißen Tag</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Kinästhetisch",
            question: "<strong>In die Hände klatschen</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        }
    ],
    dropdown_choice: [
        {
            QUD: "Kinästhetisch",
            question: "<strong>Writing your name</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Kinästhetisch",
            question: "<strong>Rising out of a low chair</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Kinästhetisch",
            question: "<strong>Running upstairs</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Kinästhetisch",
            question: "<strong>Throwing a ball</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Kinästhetisch",
            question: "<strong>Drawing a circle on paper</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Fühlen",
            question: "<strong>Wet soap</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Fühlen",
            question: "<strong>Silk</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Fühlen",
            question: "<strong>A soft, comfortable bed</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Fühlen",
            question: "<strong>The pain of a burn</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Fühlen",
            question: "<strong>The prick of a needle</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Geschmack",
            question: "<strong>Lemons</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Geschmack",
            question: "<strong>Vinegar</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Geschmack",
            question: "<strong>Chocolate</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Geschmack",
            question: "<strong>Cheese</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Geschmack",
            question: "<strong>Coffee</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Geruch",
            question: "<strong>Roses</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Geruch",
            question: "<strong>Onions</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Geruch",
            question: "<strong>Newmown grass</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Geruch",
            question: "<strong>Fresh paint</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Geruch",
            question: "<strong>Coffee</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Organisch",
            question: "<strong>Fatigue</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Organisch",
            question: "<strong>Thirst</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Organisch",
            question: "<strong>A headache</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Organisch",
            question: "<strong>A sore Throat</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Organisch",
            question: "<strong>Nausea</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Visuell",
            question: "<strong>The color of toasted bread</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Visuell",
            question: "<strong>The sun as it is sinking below the horizon</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Visuell",
            question: "<strong>The stars on a clear winter night</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Visuell",
            question: "<strong>The lights of a city through the darkness</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Visuell",
            question: "<strong>The precise eyecolor of a close friend or family member of yours</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Auditiv",
            question: "<strong>A familiar song being played on a piano</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Auditiv",
            question: "<strong>Your own voice singing</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Auditiv",
            question: "<strong>The beat of rain against the window</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Auditiv",
            question: "<strong>The clink of glasses</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        },
        {
            QUD: "Auditiv",
            question: "<strong>The mewing of a cat</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar",
            option8: "Verstehe ich nicht"
        }
    ],
    dropdown_choice_d: [
        {
            QUD: "Kinästhetisch",
            question: "<strong>Den eigenen Namen schreiben</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Kinästhetisch",
            question: "<strong>Aus einem tiefen Stuhl aufstehen</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Kinästhetisch",
            question: "<strong>Eine Treppe hochrennen</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Kinästhetisch",
            question: "<strong>Einen Ball werfen</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Kinästhetisch",
            question: "<strong>Einen Kreis auf ein Blatt Papier malen</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Fühlen",
            question: "<strong>Feuchte Seife</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Fühlen",
            question: "<strong>Seide</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Fühlen",
            question: "<strong>Ein weiches, komfortables Bett</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Fühlen",
            question: "<strong>Der Schmerz einer Verbrennung</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Fühlen",
            question: "<strong>Der Stich einer Nadel</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Geschmack",
            question: "<strong>Zitronen</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Geschmack",
            question: "<strong>Essig</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Geschmack",
            question: "<strong>Schokolade</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Geschmack",
            question: "<strong>Käse</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Geschmack",
            question: "<strong>Kaffee</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Geruch",
            question: "<strong>Rosen</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Geruch",
            question: "<strong>Zwiebeln</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Geruch",
            question: "<strong>Frisch gemähtes Grass</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Geruch",
            question: "<strong>Frische Farbe</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Geruch",
            question: "<strong>Kaffee</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Organisch",
            question: "<strong>Ermüdung</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Organisch",
            question: "<strong>Durst</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Organisch",
            question: "<strong>Kopfschmerzen</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Organisch",
            question: "<strong>Halsschmerzen</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Organisch",
            question: "<strong>Übelkeit</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Visuell",
            question: "<strong>Die Farve eines getoasteten Brots</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Visuell",
            question: "<strong>Die Sonne, die hinter dem Horizont versinkt</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Visuell",
            question: "<strong>Die Sterne in einer klaren Winternacht</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Visuell",
            question: "<strong>Die Lichter einer Stadt in der Dunkelheit</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Visuell",
            question: "<strong>Die genaue Augenfarbe eines engen Freundes oder Familienmitglieds</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Auditiv",
            question: "<strong>Ein bekanntes Lied wie es auf dem Klavier gespielt wird</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Auditiv",
            question: "<strong>Die eigene Singstimme</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Auditiv",
            question: "<strong>Regentropfen am Fenster</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Auditiv",
            question: "<strong>Das klirren von Gläsern</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        },
        {
            QUD: "Auditiv",
            question: "<strong>Das miauen einer Katze</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Sehr klar",
            option7: "Komplett klar"
        }
    ]
};
