// In this file you can specify the trial data for your experiment

const english_version = {
    forced_choice: [
        {
            question: "Breakfast",
            option1: "Pausenbrot",
            option2: "Frühstück",
            correct: "Frühstück"

        },
        {
            question: "Cinnamon",
            option1: "Zimt",
            option2: "Stuhlbein",
            correct: "Zimt"

        },
        {
            question: "Eardrum",
            option1: "Ohrmuschel",
            option2: "Trommelfell",
            correct: "Trommelfell"

        },
        {
            question: "Forest",
            option1: "Wald",
            option2: "Holz",
            correct: "Wald"

        },
        {
            question: "Environment",
            option1: "Krankenhaus",
            option2: "Umwelt",
            correct: "Umwelt"

        }
    ],

    dropdown_choice_p: [
        {
            QUD: "Tactile",
            question: "<strong>The feeling of sweaty hands</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Gustatory",
            question: "<strong>Oranges</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Organic",
            question: "<strong>The itch of a mosquito bite</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Olfactory",
            question: "<strong>Summer rain on a hot day</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Kinesthetic",
            question: "<strong>Clapping your hands</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        }
    ],
    dropdown_choice: [
        {
            QUD: "Kinesthetic",
            question: "<strong>Writing your name</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Kinesthetic",
            question: "<strong>Rising out of a low chair</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Kinesthetic",
            question: "<strong>Running upstairs</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Kinesthetic",
            question: "<strong>Throwing a ball</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Kinesthetic",
            question: "<strong>Drawing a circle on paper</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Tactile",
            question: "<strong>Wet soap</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Tactile",
            question: "<strong>Silk</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Tactile",
            question: "<strong>A soft, comfortable bed</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Tactile",
            question: "<strong>The pain of a burn</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Tactile",
            question: "<strong>The prick of a needle</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Gustatory",
            question: "<strong>Lemons</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Gustatory",
            question: "<strong>Vinegar</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Gustatory",
            question: "<strong>Chocolate</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Gustatory",
            question: "<strong>Cheese</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Gustatory",
            question: "<strong>Coffee</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Olfactory",
            question: "<strong>Roses</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Olfactory",
            question: "<strong>Onions</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Olfactory",
            question: "<strong>Newmown grass</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Olfactory",
            question: "<strong>Fresh paint</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Olfactory",
            question: "<strong>Coffee</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Organic",
            question: "<strong>Fatigue</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Organic",
            question: "<strong>Thirst</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Organic",
            question: "<strong>A headache</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Organic",
            question: "<strong>A sore Throat</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Organic",
            question: "<strong>Nausea</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Visual",
            question: "<strong>The color of toasted bread</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Visual",
            question: "<strong>The sun as it is sinking below the horizon</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Visual",
            question: "<strong>The stars on a clear winter night</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Visual",
            question: "<strong>The lights of a city through the darkness</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Visual",
            question: "<strong>The precise eyecolor of a close friend or family member of yours</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Auditory",
            question: "<strong>A familiar song being played on a piano</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Auditory",
            question: "<strong>Your own voice singing</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Auditory",
            question: "<strong>The beat of rain against the window</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Auditory",
            question: "<strong>The clink of glasses</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        },
        {
            QUD: "Auditory",
            question: "<strong>The mewing of a cat</strong>",
            question_left_part: "How clear is your mental image?",
            option1: "No image",
            option2: "Very vague and dim",
            option3: "Vague and dim",
            option4: "Not clear, but recognizable",
            option5: "Moderately clear",
            option6: "Mostly clear",
            option7: "Perfectly clear",
            option8: "Do not understand"
        }
    ],
    sentence_choice: [
      {
        question: "Your native language is: ",
        option1: "German",
        option2: "English",
        option3: "Other"
      }
    ],
    textbox_input: [
      {
        question: "Your dominant language is: ",
        min_chars: 2
      }
    ],
  };

const german_version = {
  dropdown_choice_p: [
      {
          QUD: "Fühlen",
          question: "<strong>Das Gefühl schwitziger Hände</strong>",
          question_left_part: "Wie klar ist Ihre Vorstellung?",
          option1: "Kein Bild",
          option2: "Sehr unklar und trübe",
          option3: "Unklar und trübe",
          option4: "Nicht klar, aber erkennbar",
          option5: "Mäßig klar",
          option6: "Äußerst klar",
          option7: "Komplett klar",
          option8: ""
      },
      {
          QUD: "Geschmack",
          question: "<strong>Orangen</strong>",
          question_left_part: "Wie klar ist Ihre Vorstellung?",
          option1: "Kein Bild",
          option2: "Sehr unklar und trübe",
          option3: "Unklar und trübe",
          option4: "Nicht klar, aber erkennbar",
          option5: "Mäßig klar",
          option6: "Äußerst klar",
          option7: "Komplett klar",
          option8: ""
      },
      {
          QUD: "Organisch",
          question: "<strong>Das Jucken eines Mückenstichs</strong>",
          question_left_part: "Wie klar ist Ihre Vorstellung?",
          option1: "Kein Bild",
          option2: "Sehr unklar und trübe",
          option3: "Unklar und trübe",
          option4: "Nicht klar, aber erkennbar",
          option5: "Mäßig klar",
          option6: "Äußerst klar",
          option7: "Komplett klar",
          option8: ""
      },
      {
          QUD: "Geruch",
          question: "<strong>Sommerregen an einem heißen Tag</strong>",
          question_left_part: "Wie klar ist Ihre Vorstellung?",
          option1: "Kein Bild",
          option2: "Sehr unklar und trübe",
          option3: "Unklar und trübe",
          option4: "Nicht klar, aber erkennbar",
          option5: "Mäßig klar",
          option6: "Äußerst klar",
          option7: "Komplett klar",
          option8: ""
      },
      {
          QUD: "Kinästhetisch",
          question: "<strong>In die Hände klatschen</strong>",
          question_left_part: "Wie klar ist Ihre Vorstellung?",
          option1: "Kein Bild",
          option2: "Sehr unklar und trübe",
          option3: "Unklar und trübe",
          option4: "Nicht klar, aber erkennbar",
          option5: "Mäßig klar",
          option6: "Äußerst klar",
          option7: "Komplett klar",
          option8: ""
      }
  ],

    dropdown_choice: [
        {
            QUD: "Kinästhetisch",
            question: "<strong>Den eigenen Namen schreiben</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar ",
            option8: ""
        },
        {
            QUD: "Kinästhetisch",
            question: "<strong>Aus einem tiefen Stuhl aufstehen</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Kinästhetisch",
            question: "<strong>Eine Treppe hochrennen</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Kinästhetisch",
            question: "<strong>Einen Ball werfen</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Kinästhetisch",
            question: "<strong>Einen Kreis auf ein Blatt Papier malen</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Fühlen",
            question: "<strong>Feuchte Seife</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Fühlen",
            question: "<strong>Seide</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Fühlen",
            question: "<strong>Ein weiches, komfortables Bett</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Fühlen",
            question: "<strong>Der Schmerz einer Verbrennung</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Fühlen",
            question: "<strong>Der Stich einer Nadel</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Geschmack",
            question: "<strong>Zitronen</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Geschmack",
            question: "<strong>Essig</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Geschmack",
            question: "<strong>Schokolade</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Geschmack",
            question: "<strong>Käse</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Geschmack",
            question: "<strong>Kaffee</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Geruch",
            question: "<strong>Rosen</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Geruch",
            question: "<strong>Zwiebeln</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Geruch",
            question: "<strong>Frisch gemähtes Grass</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Geruch",
            question: "<strong>Frische Farbe</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Geruch",
            question: "<strong>Kaffee</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Organisch",
            question: "<strong>Ermüdung</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Organisch",
            question: "<strong>Durst</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Organisch",
            question: "<strong>Kopfschmerzen</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Organisch",
            question: "<strong>Halsschmerzen</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Organisch",
            question: "<strong>Übelkeit</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Visuell",
            question: "<strong>Die Farbe eines getoasteten Brots</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Visuell",
            question: "<strong>Die Sonne, die hinter dem Horizont versinkt</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Visuell",
            question: "<strong>Die Sterne in einer klaren Winternacht</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Visuell",
            question: "<strong>Die Lichter einer Stadt in der Dunkelheit</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Visuell",
            question: "<strong>Die genaue Augenfarbe eines engen Freundes oder Familienmitglieds</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Auditiv",
            question: "<strong>Ein bekanntes Lied wie es auf dem Klavier gespielt wird</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Auditiv",
            question: "<strong>Die eigene Singstimme</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Auditiv",
            question: "<strong>Regentropfen am Fenster</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Auditiv",
            question: "<strong>Das klirren von Gläsern</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        },
        {
            QUD: "Auditiv",
            question: "<strong>Das miauen einer Katze</strong>",
            question_left_part: "Wie klar ist Ihre Vorstellung?",
            option1: "Kein Bild",
            option2: "Sehr unklar und trübe",
            option3: "Unklar und trübe",
            option4: "Nicht klar, aber erkennbar",
            option5: "Mäßig klar",
            option6: "Äußerst klar",
            option7: "Komplett klar",
            option8: ""
        }
    ],
    sentence_choice: [
      {
        question: "Ihre Muttersprache ist: ",
        option1: "Deutsch",
        option2: "Englisch",
        option3: "Andere"
      }
    ],
    textbox_input: [
      {
        question: "Ihre dominante Sprache ist: ",
        min_chars: 2
      }
    ],
  };
